version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - /data/docker-postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

